// Node catalog — drives the palette + the config panel.
// Sprint-1 nodes are implemented; later-sprint nodes are listed so the canvas
// can show what's coming. The engine runs a safe pass-through for the stubs.

import type { NodeCatalogEntry } from "./types";

export const NODE_CATALOG: NodeCatalogEntry[] = [
  {
    type: "manualTrigger",
    group: "trigger",
    name: "Manual / Test",
    icon: "mouse-pointer-click",
    implemented: true,
    outputs: 1,
    description: "Starts the workflow when you press Run.",
    params: [],
  },
  {
    type: "httpRequest",
    group: "action",
    name: "HTTP Request",
    icon: "globe",
    implemented: true,
    outputs: 1,
    description: "Call external API",
    params: [
      {
        key: "method",
        label: "Method",
        control: "select",
        options: ["GET", "POST", "PUT", "PATCH", "DELETE"],
        default: "GET",
      },
      {
        key: "url",
        label: "URL",
        control: "string",
        default: "",
        help: "Supports expressions, e.g. https://api.x.com/users/{{ $json.id }}",
      },
      { key: "headers", label: "Headers", control: "json", default: {} },
      {
        key: "bodyType",
        label: "Body type",
        control: "select",
        options: ["none", "json", "raw"],
        default: "none",
      },
      {
        key: "body",
        label: "Body",
        control: "text",
        default: "",
        showWhen: { key: "bodyType", in: ["json", "raw"] },
      },
    ],
  },
  {
    type: "wait",
    group: "action",
    name: "Wait",
    icon: "timer",
    implemented: true,
    outputs: 1,
    description: "Pause before the next step (capped at 15s in v1).",
    params: [
      { key: "amount", label: "Amount", control: "number", default: 1 },
      {
        key: "unit",
        label: "Unit",
        control: "select",
        options: ["seconds", "minutes", "hours"],
        default: "seconds",
      },
    ],
  },
  {
    type: "if",
    group: "logic",
    name: "IF",
    icon: "git-branch",
    implemented: true,
    outputs: 2,
    description: "Split into True/False",
    params: [
      { key: "value1", label: "Value 1", control: "string", default: "" },
      {
        key: "operator",
        label: "Operator",
        control: "select",
        options: [
          "equal",
          "notEqual",
          "contains",
          "notContains",
          "isEmpty",
          "isNotEmpty",
          "gt",
          "lt",
          "gte",
          "lte",
          "regex",
        ],
        default: "equal",
      },
      { key: "value2", label: "Value 2", control: "string", default: "" },
    ],
  },
  {
    type: "set",
    group: "action",
    name: "Edit Fields (Set)",
    icon: "pencil",
    implemented: true,
    outputs: 1,
    description: "Modify data",
    params: [
      { key: "assignments", label: "Fields", control: "fieldlist", default: [] },
      {
        key: "keepOnlySet",
        label: "Keep only these fields",
        control: "bool",
        default: false,
      },
    ],
  },
  {
    type: "webhookTrigger",
    group: "trigger",
    name: "Webhook",
    icon: "webhook",
    implemented: true,
    outputs: 1,
    description: "Starts workflow on event",
    params: [
      {
        key: "method",
        label: "Method",
        control: "select",
        options: ["POST", "GET", "PUT", "PATCH", "DELETE"],
        default: "POST",
      },
      {
        key: "auth",
        label: "Auth",
        control: "select",
        options: ["none", "header secret"],
        default: "none",
      },
      {
        key: "responseMode",
        label: "Respond",
        control: "select",
        options: ["immediately", "usingRespondNode"],
        default: "immediately",
      },
    ],
  },
  {
    type: "formTrigger",
    group: "trigger",
    name: "Form",
    icon: "clipboard-list",
    implemented: true,
    outputs: 1,
    description: "Give people a hosted form; submitting it starts the workflow.",
    params: [
      { key: "title", label: "Form title", control: "string", default: "Untitled form" },
      { key: "description", label: "Description", control: "text", default: "" },
      {
        key: "fields",
        label: "Fields",
        control: "formfields",
        default: [{ label: "Email", type: "email", required: true }],
      },
      {
        key: "submitMessage",
        label: "Submit message",
        control: "string",
        default: "Thanks! We got it.",
      },
    ],
  },
  {
    type: "respondToWebhook",
    group: "action",
    name: "Respond to Webhook",
    icon: "reply",
    implemented: true,
    outputs: 1,
    description: "Return a custom HTTP response to a webhook caller.",
    params: [
      { key: "statusCode", label: "Status code", control: "number", default: 200 },
      {
        key: "bodyType",
        label: "Body type",
        control: "select",
        options: ["json", "text"],
        default: "json",
      },
      { key: "body", label: "Body", control: "text", default: '{ "ok": true }' },
    ],
  },
  {
    type: "scheduleTrigger",
    group: "trigger",
    name: "Schedule Trigger",
    icon: "clock",
    implemented: true,
    outputs: 1,
    description: "Runs on a timer",
    params: [
      {
        key: "mode",
        label: "Trigger interval",
        control: "select",
        options: ["seconds", "minutes", "hours", "days", "cron"],
        default: "minutes",
      },
      {
        key: "every",
        label: "Every",
        control: "number",
        default: 5,
        showWhen: { key: "mode", in: ["seconds", "minutes", "hours", "days"] },
      },
      {
        key: "cron",
        label: "Cron expression",
        control: "string",
        default: "0 * * * *",
        showWhen: { key: "mode", in: ["cron"] },
      },
    ],
  },
  {
    type: "callCompletedTrigger",
    group: "trigger",
    name: "Call Completed",
    icon: "phone-call",
    implemented: true,
    outputs: 1,
    description: "Fires when an AI voice call ends — transcript, outcome & caller.",
    params: [
      {
        key: "agent",
        label: "Agent / flow id",
        control: "string",
        default: "",
        help: "Blank = all agents. Otherwise the flow id (matches body.agent.id), e.g. durdans.",
      },
      {
        key: "direction",
        label: "Direction",
        control: "select",
        options: ["any", "inbound", "outbound"],
        default: "any",
      },
      {
        key: "auth",
        label: "Auth",
        control: "select",
        options: ["none", "header secret"],
        default: "none",
      },
    ],
  },
  {
    type: "googleSheets",
    group: "action",
    name: "Google Sheets",
    icon: "file-spreadsheet",
    implemented: true,
    outputs: 1,
    description: "Read/Write rows",
    params: [
      {
        key: "operation",
        label: "Operation",
        control: "select",
        options: ["append", "read", "update", "delete"],
        default: "append",
      },
      { key: "documentId", label: "Spreadsheet ID / URL", control: "string", default: "" },
      { key: "sheetName", label: "Sheet name", control: "string", default: "Sheet1" },
    ],
  },
  {
    type: "code",
    group: "action",
    name: "Code",
    icon: "terminal",
    implemented: true,
    outputs: 1,
    description: "Custom JS/Python",
    params: [
      {
        key: "language",
        label: "Language",
        control: "select",
        options: ["JavaScript", "Python"],
        default: "JavaScript",
      },
      {
        key: "code",
        label: "Code",
        control: "text",
        default: "// each row is an item; return the items array\nreturn items;",
      },
    ],
  },
  {
    type: "openAi",
    group: "action",
    name: "OpenAI",
    icon: "sparkles",
    implemented: true,
    outputs: 1,
    description: "Generate/Parse text",
    params: [
      {
        key: "resource",
        label: "Resource",
        control: "select",
        options: ["Chat", "Text", "Image"],
        default: "Chat",
      },
      {
        key: "model",
        label: "Model",
        control: "select",
        options: ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo"],
        default: "gpt-4o-mini",
      },
      {
        key: "prompt",
        label: "Prompt",
        control: "text",
        default: "",
        help: "Supports expressions, e.g. Summarise {{ $json.text }}",
      },
    ],
  },
];

export const NODE_TYPES: Record<string, NodeCatalogEntry> = Object.fromEntries(
  NODE_CATALOG.map((n) => [n.type, n]),
);

export function isKnownNodeType(type: unknown): type is string {
  return typeof type === "string" && Object.hasOwn(NODE_TYPES, type);
}
